import type { Subject } from "./types";

const s = (id: string, name: string, color: string, topics: string[]): Subject => ({
  id,
  name,
  color,
  hours: 0,
  topics: topics.map((t, i) => ({
    id: `${id}-${i}`,
    name: t,
    status: "not_started" as const,
  })),
});

export const DEFAULT_SUBJECTS: Subject[] = [
  s("math", "Engineering Mathematics", "text-blue-500", [
    "Discrete Mathematics",
    "Propositional & First Order Logic",
    "Sets, Relations, Functions",
    "Partial Orders & Lattices",
    "Groups",
    "Graphs: Connectivity, Coloring, Matching",
    "Combinatorics",
    "Linear Algebra",
    "Matrices, Determinants",
    "Eigenvalues & Eigenvectors",
    "LU Decomposition",
    "Calculus - Limits, Continuity",
    "Differentiability, Maxima Minima",
    "Mean Value Theorems, Integration",
    "Probability & Statistics",
    "Random Variables, Distributions",
    "Mean, Median, Mode, Variance",
    "Conditional Probability, Bayes",
  ]),
  s("dl", "Digital Logic", "text-purple-500", [
    "Boolean Algebra",
    "Combinational Circuits",
    "Sequential Circuits",
    "Minimization (K-Maps)",
    "Number Representations",
    "Fixed & Floating Point",
  ]),
  s("coa", "Computer Organization & Architecture", "text-orange-500", [
    "Machine Instructions & Addressing Modes",
    "ALU & Datapath",
    "CPU Control Design",
    "Instruction Pipelining",
    "Pipeline Hazards",
    "Memory Hierarchy",
    "Cache Memory",
    "Main Memory & Secondary Storage",
    "I/O Interface (Interrupt & DMA)",
  ]),
  s("pds", "Programming & Data Structures", "text-green-500", [
    "Programming in C",
    "Recursion",
    "Arrays, Stacks, Queues",
    "Linked Lists",
    "Trees, Binary Search Trees",
    "Binary Heaps",
    "Graphs",
    "Hashing",
  ]),
  s("algo", "Algorithms", "text-emerald-500", [
    "Asymptotic Analysis",
    "Searching, Sorting",
    "Divide and Conquer",
    "Greedy Algorithms",
    "Dynamic Programming",
    "Graph Traversals",
    "Minimum Spanning Trees",
    "Shortest Paths",
  ]),
  s("toc", "Theory of Computation", "text-yellow-500", [
    "Regular Expressions & Finite Automata",
    "Context-Free Grammars & PDA",
    "Regular & Context-Free Languages",
    "Pumping Lemma",
    "Turing Machines",
    "Undecidability",
  ]),
  s("cd", "Compiler Design", "text-amber-500", [
    "Lexical Analysis",
    "Parsing",
    "Syntax Directed Translation",
    "Runtime Environments",
    "Intermediate Code Generation",
    "Local Optimization",
    "Data Flow Analysis",
  ]),
  s("os", "Operating Systems", "text-cyan-500", [
    "Processes",
    "Threads",
    "Inter-process Communication",
    "CPU Scheduling",
    "Synchronization",
    "Deadlocks",
    "Memory Management",
    "Paging",
    "Segmentation",
    "Virtual Memory",
    "File Systems",
    "Disk Scheduling",
  ]),
  s("dbms", "Databases", "text-indigo-500", [
    "ER Model",
    "Relational Model & Algebra",
    "Tuple Calculus, SQL",
    "Integrity Constraints",
    "Normal Forms",
    "File Organization, Indexing",
    "B & B+ Trees",
    "Transactions & Concurrency",
  ]),
  s("cn", "Computer Networks", "text-rose-500", [
    "Concept of Layering (OSI/TCP-IP)",
    "Data Link Layer, Switching",
    "IPv4/IPv6, Routers",
    "Routing Algorithms",
    "TCP & UDP",
    "Sockets, Congestion Control",
    "Application Layer (DNS, HTTP, SMTP)",
    "Network Security Basics",
  ]),
  s("apt", "General Aptitude", "text-pink-500", [
    "Verbal Aptitude",
    "Quantitative Aptitude",
    "Analytical Aptitude",
    "Spatial Aptitude",
    "Data Interpretation",
    "Logical Reasoning",
  ]),
];
